// Languages supported by Google Input Tools for transliteration
export const transliterationLanguages = {
  'hi': 'Hindi',
  'bn': 'Bengali', 
  'gu': 'Gujarati',
  'kn': 'Kannada',
  'ml': 'Malayalam',
  'mr': 'Marathi',
  'ne': 'Nepali',
  'or': 'Odia',
  'pa': 'Punjabi',
  'sa': 'Sanskrit',
  'si': 'Sinhala',
  'ta': 'Tamil',
  'te': 'Telugu',
  'ur': 'Urdu',
  'ar': 'Arabic',
  'fa': 'Persian',
  'he': 'Hebrew',
  'th': 'Thai',
  'zh': 'Chinese',
  'ja': 'Japanese',
  'ko': 'Korean',
  'el': 'Greek',
  'ru': 'Russian',
  'bg': 'Bulgarian',
  'uk': 'Ukrainian',
  'sr': 'Serbian',
  'mk': 'Macedonian',
  'mn': 'Mongolian',
  'ka': 'Georgian',
  'hy': 'Armenian',
  'am': 'Amharic',
  'ti': 'Tigrinya',
  'dv': 'Dhivehi',
  'bo': 'Tibetan',
  'ug': 'Uyghur'
};

// Google Input Tools language codes for transliteration
export const transliterationCodes = {
  'hi': 'hi-t-i0-und', // Hindi
  'bn': 'bn-t-i0-und', // Bengali
  'gu': 'gu-t-i0-und', // Gujarati
  'kn': 'kn-t-i0-und', // Kannada
  'ml': 'ml-t-i0-und', // Malayalam
  'mr': 'mr-t-i0-und', // Marathi
  'ne': 'ne-t-i0-und', // Nepali
  'or': 'or-t-i0-und', // Odia
  'pa': 'pa-t-i0-und', // Punjabi
  'sa': 'sa-t-i0-und', // Sanskrit
  'si': 'si-t-i0-und', // Sinhala
  'ta': 'ta-t-i0-und', // Tamil
  'te': 'te-t-i0-und', // Telugu
  'ur': 'ur-t-i0-und', // Urdu
  'ar': 'ar-t-i0-und', // Arabic
  'fa': 'fa-t-i0-und', // Persian
  'he': 'he-t-i0-und', // Hebrew
  'th': 'th-t-i0-und', // Thai
  'zh': 'zh-t-i0-und', // Chinese
  'ja': 'ja-t-i0-und', // Japanese
  'ko': 'ko-t-i0-und', // Korean
  'el': 'el-t-i0-und', // Greek
  'ru': 'ru-t-i0-und', // Russian
  'bg': 'bg-t-i0-und', // Bulgarian
  'uk': 'uk-t-i0-und', // Ukrainian
  'sr': 'sr-t-i0-und', // Serbian
  'mk': 'mk-t-i0-und', // Macedonian
  'mn': 'mn-t-i0-und', // Mongolian
  'ka': 'ka-t-i0-und', // Georgian
  'hy': 'hy-t-i0-und', // Armenian
  'am': 'am-t-i0-und', // Amharic
  'ti': 'ti-t-i0-und', // Tigrinya
  'dv': 'dv-t-i0-und', // Dhivehi
  'bo': 'bo-t-i0-und', // Tibetan
  'ug': 'ug-t-i0-und'  // Uyghur
};

// Languages supported by MyMemory Translation API
export const supportedLanguages = {
  // Major world languages
  'en': 'English',
  'es': 'Spanish',
  'fr': 'French',
  'de': 'German',
  'it': 'Italian',
  'pt': 'Portuguese',
  'ru': 'Russian',
  'ja': 'Japanese',
  'ko': 'Korean',
  'zh': 'Chinese',
  'ar': 'Arabic',
  'tr': 'Turkish',
  'nl': 'Dutch',
  'sv': 'Swedish',
  'da': 'Danish',
  'no': 'Norwegian',
  'fi': 'Finnish',
  'pl': 'Polish',
  'cs': 'Czech',
  'sk': 'Slovak',
  'hu': 'Hungarian',
  'ro': 'Romanian',
  'bg': 'Bulgarian',
  'hr': 'Croatian',
  'sr': 'Serbian',
  'sl': 'Slovenian',
  'et': 'Estonian',
  'lv': 'Latvian',
  'lt': 'Lithuanian',
  'mt': 'Maltese',
  'el': 'Greek',
  'he': 'Hebrew',
  'th': 'Thai',
  'vi': 'Vietnamese',
  'id': 'Indonesian',
  'ms': 'Malay',
  'tl': 'Filipino',
  'sw': 'Swahili',
  'af': 'Afrikaans',
  'is': 'Icelandic',
  'ga': 'Irish',
  'cy': 'Welsh',
  'eu': 'Basque',
  'ca': 'Catalan',
  'gl': 'Galician',
  'mk': 'Macedonian',
  'sq': 'Albanian',
  'bs': 'Bosnian',
  'me': 'Montenegrin',
  'ka': 'Georgian',
  'hy': 'Armenian',
  'az': 'Azerbaijani',
  'kk': 'Kazakh',
  'ky': 'Kyrgyz',
  'uz': 'Uzbek',
  'tg': 'Tajik',
  'mn': 'Mongolian',
  'ne': 'Nepali',
  'si': 'Sinhala',
  'my': 'Burmese',
  'km': 'Khmer',
  'lo': 'Lao',
  'am': 'Amharic',
  'ha': 'Hausa',
  'yo': 'Yoruba',
  'ig': 'Igbo',
  'zu': 'Zulu',
  'xh': 'Xhosa',
  'st': 'Southern Sotho',
  'tn': 'Tswana',
  'ss': 'Swati',
  've': 'Venda',
  'ts': 'Tsonga',
  'sn': 'Shona',
  'rw': 'Kinyarwanda',
  'mg': 'Malagasy',
  'so': 'Somali',
  'om': 'Oromo',
  'ti': 'Tigrinya',
  'be': 'Belarusian',
  'uk': 'Ukrainian',
  'fa': 'Persian',
  'ps': 'Pashto',
  'ku': 'Kurdish',
  'sd': 'Sindhi',
  
  // Indian languages
  'hi': 'Hindi',
  'bn': 'Bengali',
  'gu': 'Gujarati',
  'pa': 'Punjabi',
  'or': 'Odia',
  'as': 'Assamese',
  'ml': 'Malayalam',
  'ta': 'Tamil',
  'te': 'Telugu',
  'kn': 'Kannada',
  'mr': 'Marathi',
  'sa': 'Sanskrit',
  'dv': 'Dhivehi',
  'bo': 'Tibetan',
  'ug': 'Uyghur',
  'ur': 'Urdu'
};

// Speech recognition language codes
export const speechRecognitionLanguages = {
  'en': 'en-US',
  'en-US': 'en-US',
  'en-GB': 'en-GB',
  'en-CA': 'en-CA',
  'en-AU': 'en-AU',
  'en-NZ': 'en-NZ',
  'en-IE': 'en-IE',
  'en-ZA': 'en-ZA',
  'es': 'es-ES',
  'es-ES': 'es-ES',
  'es-MX': 'es-MX',
  'fr': 'fr-FR',
  'fr-FR': 'fr-FR',
  'fr-CA': 'fr-CA',
  'de': 'de-DE',
  'de-DE': 'de-DE',
  'it': 'it-IT',
  'it-IT': 'it-IT',
  'pt': 'pt-PT',
  'pt-PT': 'pt-PT',
  'pt-BR': 'pt-BR',
  'ru': 'ru-RU',
  'ru-RU': 'ru-RU',
  'ja': 'ja-JP',
  'ja-JP': 'ja-JP',
  'ko': 'ko-KR',
  'ko-KR': 'ko-KR',
  'zh': 'zh-CN',
  'zh-CN': 'zh-CN',
  'zh-TW': 'zh-TW',
  'ar': 'ar-SA',
  'ar-SA': 'ar-SA',
  'hi': 'hi-IN',
  'hi-IN': 'hi-IN',
  'bn': 'bn-IN',
  'bn-IN': 'bn-IN',
  'ur': 'ur-PK',
  'ur-PK': 'ur-PK',
  'tr': 'tr-TR',
  'tr-TR': 'tr-TR',
  'nl': 'nl-NL',
  'nl-NL': 'nl-NL',
  'sv': 'sv-SE',
  'sv-SE': 'sv-SE',
  'da': 'da-DK',
  'da-DK': 'da-DK',
  'no': 'no-NO',
  'no-NO': 'no-NO',
  'fi': 'fi-FI',
  'fi-FI': 'fi-FI',
  'pl': 'pl-PL',
  'pl-PL': 'pl-PL',
  'cs': 'cs-CZ',
  'cs-CZ': 'cs-CZ',
  'sk': 'sk-SK',
  'sk-SK': 'sk-SK',
  'hu': 'hu-HU',
  'hu-HU': 'hu-HU',
  'ro': 'ro-RO',
  'ro-RO': 'ro-RO',
  'bg': 'bg-BG',
  'bg-BG': 'bg-BG',
  'hr': 'hr-HR',
  'hr-HR': 'hr-HR',
  'sr': 'sr-RS',
  'sr-RS': 'sr-RS',
  'sl': 'sl-SI',
  'sl-SI': 'sl-SI',
  'et': 'et-EE',
  'et-EE': 'et-EE',
  'lv': 'lv-LV',
  'lv-LV': 'lv-LV',
  'lt': 'lt-LT',
  'lt-LT': 'lt-LT',
  'mt': 'mt-MT',
  'mt-MT': 'mt-MT',
  'el': 'el-GR',
  'el-GR': 'el-GR',
  'he': 'he-IL',
  'he-IL': 'he-IL',
  'th': 'th-TH',
  'th-TH': 'th-TH',
  'vi': 'vi-VN',
  'vi-VN': 'vi-VN',
  'id': 'id-ID',
  'id-ID': 'id-ID',
  'ms': 'ms-MY',
  'ms-MY': 'ms-MY',
  'tl': 'tl-PH',
  'tl-PH': 'tl-PH',
  'sw': 'sw-KE',
  'sw-KE': 'sw-KE',
  'af': 'af-ZA',
  'af-ZA': 'af-ZA',
  'is': 'is-IS',
  'is-IS': 'is-IS',
  'ga': 'ga-IE',
  'ga-IE': 'ga-IE',
  'cy': 'cy-GB',
  'cy-GB': 'cy-GB',
  'eu': 'eu-ES',
  'eu-ES': 'eu-ES',
  'ca': 'ca-ES',
  'ca-ES': 'ca-ES',
  'gl': 'gl-ES',
  'gl-ES': 'gl-ES',
  'mk': 'mk-MK',
  'mk-MK': 'mk-MK',
  'sq': 'sq-AL',
  'sq-AL': 'sq-AL',
  'bs': 'bs-BA',
  'bs-BA': 'bs-BA',
  'me': 'me-ME',
  'me-ME': 'me-ME',
  'ka': 'ka-GE',
  'ka-GE': 'ka-GE',
  'hy': 'hy-AM',
  'hy-AM': 'hy-AM',
  'az': 'az-AZ',
  'az-AZ': 'az-AZ',
  'kk': 'kk-KZ',
  'kk-KZ': 'kk-KZ',
  'ky': 'ky-KG',
  'ky-KG': 'ky-KG',
  'uz': 'uz-UZ',
  'uz-UZ': 'uz-UZ',
  'tg': 'tg-TJ',
  'tg-TJ': 'tg-TJ',
  'mn': 'mn-MN',
  'mn-MN': 'mn-MN',
  'ne': 'ne-NP',
  'ne-NP': 'ne-NP',
  'si': 'si-LK',
  'si-LK': 'si-LK',
  'my': 'my-MM',
  'my-MM': 'my-MM',
  'km': 'km-KH',
  'km-KH': 'km-KH',
  'lo': 'lo-LA',
  'lo-LA': 'lo-LA',
  'am': 'am-ET',
  'am-ET': 'am-ET',
  'ha': 'ha-NG',
  'ha-NG': 'ha-NG',
  'yo': 'yo-NG',
  'yo-NG': 'yo-NG',
  'ig': 'ig-NG',
  'ig-NG': 'ig-NG',
  'zu': 'zu-ZA',
  'zu-ZA': 'zu-ZA',
  'xh': 'xh-ZA',
  'xh-ZA': 'xh-ZA',
  'st': 'st-ZA',
  'st-ZA': 'st-ZA',
  'tn': 'tn-BW',
  'tn-BW': 'tn-BW',
  'ss': 'ss-SZ',
  'ss-SZ': 'ss-SZ',
  've': 've-ZA',
  've-ZA': 've-ZA',
  'ts': 'ts-ZA',
  'ts-ZA': 'ts-ZA',
  'sn': 'sn-ZW',
  'sn-ZW': 'sn-ZW',
  'rw': 'rw-RW',
  'rw-RW': 'rw-RW',
  'mg': 'mg-MG',
  'mg-MG': 'mg-MG',
  'so': 'so-SO',
  'so-SO': 'so-SO',
  'om': 'om-ET',
  'om-ET': 'om-ET',
  'ti': 'ti-ER',
  'ti-ER': 'ti-ER',
  'be': 'be-BY',
  'be-BY': 'be-BY',
  'uk': 'uk-UA',
  'uk-UA': 'uk-UA',
  'fa': 'fa-IR',
  'fa-IR': 'fa-IR',
  'ps': 'ps-AF',
  'ps-AF': 'ps-AF',
  'ku': 'ku-TR',
  'ku-TR': 'ku-TR',
  'sd': 'sd-PK',
  'sd-PK': 'sd-PK',
  'gu': 'gu-IN',
  'gu-IN': 'gu-IN',
  'pa': 'pa-IN',
  'pa-IN': 'pa-IN',
  'or': 'or-IN',
  'or-IN': 'or-IN',
  'as': 'as-IN',
  'as-IN': 'as-IN',
  'ml': 'ml-IN',
  'ml-IN': 'ml-IN',
  'ta': 'ta-IN',
  'ta-IN': 'ta-IN',
  'te': 'te-IN',
  'te-IN': 'te-IN',
  'kn': 'kn-IN',
  'kn-IN': 'kn-IN',
  'mr': 'mr-IN',
  'mr-IN': 'mr-IN',
  'sa': 'sa-IN',
  'sa-IN': 'sa-IN',
  'dv': 'dv-MV',
  'dv-MV': 'dv-MV',
  'bo': 'bo-CN',
  'bo-CN': 'bo-CN',
  'ug': 'ug-CN',
  'ug-CN': 'ug-CN'
};

// Helper function to check if a language supports transliteration
export const supportsTransliteration = (langCode) => {
  return langCode in transliterationLanguages;
};

// Helper function to get transliteration code
export const getTransliterationCode = (langCode) => {
  return transliterationCodes[langCode] || null;
};

// Helper function to check if a language is supported for translation
export const isTranslationSupported = (langCode) => {
  return langCode in supportedLanguages;
}; 